In [ ]:
from google.colab import drive
drive.mount('/drive')
import pandas as pd
import numpy as np
import json
import ast
from tqdm.notebook import tqdm
tqdm.pandas()

Mounted at /drive

## Prerequisite
1. Your HOME directory has following files:
- user.json
<br/>
2. user.json has 6 columns: 
```
user_id.$oid
major.$oid
name
username
npm
batch
last_update_course_request_at.$date
```
## Execution
Just `Run All` cells and you will get the csv result placed in your HOME directory

In [ ]:
HOME = "/drive/My Drive/Susun Jadwal/"

In [ ]:
f = open(HOME+"user.json", "r")
user = pd.json_normalize(json.load(f)).rename(columns={"_id.$oid":"user_id", "major.$oid": "major", 
                                                       "last_update_course_request_at.$date": "last_update_course_at"})
user = user.iloc[:,:-2]
user.head(2)

,name,username,npm,batch,user_id,major,last_update_course_at
0,Fahdii Ajmalal Fikrie,fahdii.ajmalal91,1906398370,2019,60f4f2b38cd53dc0e3b371ba,60f4f2b38cd53dc0e3b371b9,2021-08-03T06:03:53.099Z
1,JONATHAN FILBERT LISYANTO,Jonathan.filbert81,1806191692,2018,60f4f3068cd53dc0e3b371bd,60f4f3068cd53dc0e3b371bc,2021-08-10T01:35:58.502Z

In [ ]:
user.to_csv(HOME+'user.csv', index=False)